export const UPDATE_APP_THEME = "UPDATE_APP_THEME";

export const UPDATE_CONNECTIVITY_STATUS = "UPDATE_CONNECTIVITY_STATUS";
export const UPDATE_CONNECTIVITY_STRENGTH = "UPDATE_CONNECTIVITY_STRENGTH";

export const SHOW_LOADER_MODAL = "SHOW_TRANSPARENT_LOADER_MODAL";
export const HIDE_LOADER_MODAL = "HIDE_TRANSPARENT_LOADER_MODAL";

export const LOGIN_USER = "LOGIN_USER";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";